version: "3.9"

services:
  db:
    image: postgres:15
    container_name: logistics-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logistics_exceptions
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: logistics-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/logistics_exceptions
      PORT: 3001
    ports:
      - "3001:3001"

  web:
    build: ./web
    container_name: logistics-web
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    ports:
      - "3000:3000"

volumes:
  pgdata: